name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install the dependencies
      run: npm install
    - name: Run unit test
      run: npm run test:unit
    - name: Display SoftUni name
      run: echo "silvestari12"
      
  build_ui_test:

    runs-on: ubuntu-latest
    needs: build_test

    steps:
    - name: Checkout the repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install the dependencies
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install 
    - name: Run UI test
      run: npm run test:ui
    